version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grid-bot-helper
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:your-app-key-here
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    networks:
      - grid-bot-network

  # Opcional: Nginx como proxy reverso para mejor rendimiento
  nginx:
    image: nginx:alpine
    container_name: grid-bot-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    depends_on:
      - app
    networks:
      - grid-bot-network
    profiles:
      - nginx

networks:
  grid-bot-network:
    driver: bridge

volumes:
  storage_data:
  database_data: